spring:
  application:
    name: ResucueSync

  datasource:
    url: jdbc:postgresql://localhost:5432/rescue_sync
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: chamodi3797@gmail.com
    password: edfv zjjj bzrq kbwf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
